version: '3.7'

services: 
  web:
    build:
      context: ./
      dockerfile: Dockerfile.static
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - db_volume:/usr/src/app/db
    ports: 
      - 8000:8000
    env_file: 
      - ./.env.static.dev

  # db:
  #   image: postgres:12.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=blog_project

volumes:
  db_volume: